#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    SETPOT,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  GRN,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  YEL,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  BT1,            sensorDigitalIn)
#pragma config(Sensor, dgtl4,  BT2,            sensorDigitalIn)
#pragma config(Motor,  port2,           TLM,           tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           TRM,           tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           BLM,           tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           BRM,           tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           AL,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           AR,            tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           AG,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           AM,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		//Drive
		motor[TLM] = vexRT[Ch3];
		motor[TRM] = vexRT[Ch2];
		motor[BLM] = vexRT[Ch3];
		motor[BRM] = vexRT[Ch2];

		//arm
		if(vexRT[Btn6U] == true){
			motor[AR] = 127;
			motor[AL] = 127;
		}

		else if(vexRT[Btn6D] == true){
			motor[AR] = -127;
			motor[AL] = -127;
		}

		else if(vexRT[Btn5U] == true){
			motor[AM] = 127;
		}
		else if(vexRT[Btn5D] == true){
			motor[AM] = -127;
		}
		else if(vexRT[Btn8U] == true){
			motor[AG] = 127;
		}
		else if(vexRT[Btn8D] == true){
			motor[AG] = -127;
		}
		else{
			motor[AG] = 0;
			motor[AM] = 0;
			motor[AR] = 0;
			motor[AL] = 0;
		}
	}
}
