#pragma config(Sensor, in1,    GY1,            sensorGyro)
#pragma config(Sensor, dgtl1,  gyrde,          sensorDigitalIn)
#pragma config(Sensor, dgtl2,  ,               sensorLEDtoVCC)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           FR,            tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           BBL,           tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           BBR,           tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           CL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           CR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "BSREV3A.h"
#include "Vex_Competition_Includes.c"
#pragma platform(VEX2)
#pragma competitionControl(Competition)

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	haminit();
	clrlcd();
	while (true)
	{
		rstate();
		batlev(false);
		motor[FL] = vexRT[Ch1] + vexRT[Ch2];
		motor[FR] = vexRT[Ch1] - vexRT[Ch2];
		motor[BBL]= vexRT[Ch1] - vexRT[Ch2];
		motor[BBR]= vexRT[Ch1] - vexRT[Ch2];
		if(vexRT[Btn6D]==true){
			motor[CL] = 127;
			motor[CR] = 127;
		}
		else if(vexRT[Btn6U]==true){
			motor[CL] = -127;
			motor[CR] = -127;
		}
		else{
			motor[CL] = 0;
			motor[CR] = 0;
		}
		if (SensorValue[dgtl1]==false)
		{
			wait1Msec(10);
			if (lcswi == true)
			{
				lcswi=false;
			}
			else
			{
				lcswi=true;
			}
		}

	}
}
